require("gitsigns").setup({
	signs = {
		add = {
			hl = "GitSignsAdd",
			text = "▎",
			numhl = "GitSignsAddNr",
			linehl = "GitSignsAddLn",
		},
		change = {
			hl = "GitSignsChange",
			text = "▎",
			numhl = "GitSignsChangeNr",
			linehl = "GitSignsChangeLn",
		},
		delete = {
			hl = "GitSignsDelete",
			text = "契",
			numhl = "GitSignsDeleteNr",
			linehl = "GitSignsDeleteLn",
		},
		topdelete = {
			hl = "GitSignsDelete",
			text = "契",
			numhl = "GitSignsDeleteNr",
			linehl = "GitSignsDeleteLn",
		},
		changedelete = {
			hl = "GitSignsChange",
			text = "▎",
			numhl = "GitSignsChangeNr",
			linehl = "GitSignsChangeLn",
		},
	},
	numhl = false,
	linehl = false,
	word_diff = false,
	signcolumn = true,
	attach_to_untracked = true,
	current_line_blame = false,
	watch_gitdir = { interval = 1000, follow_files = true },
	current_line_blame_opts = {
		delay = 1000,
		virt_text = true,
		virt_text_pos = "eol",
		ignore_whitespace = false,
	},
	current_line_blame_formatter_opts = { relative_time = false },
	sign_priority = 6,
	update_debounce = 100,
	status_formatter = nil,
	max_file_length = 40000,
	preview_config = {
		row = 0,
		col = 1,
		border = "single",
		style = "minimal",
		relative = "cursor",
	},
	yadm = { enable = false },
})
