require("nvim-treesitter.configs").setup({
        ensure_installed = {
            "c",
            "go",
            "org",
            "cpp",
            "css",
            "lua",
            "rust",
            "cuda",
            "bash",
            "json",
            "yaml",
            "toml",
            "html",
            "scss",
            "make",
            "cmake",
            "julia",
            "latex",
            "python",
            "fortran",
            "markdown",
            "javascript",
            "dockerfile",
        },
    sync_install = true,
    indent = { enable = true },
    autopairs = { enable = true },
    context_commentstring = { enable = true, enable_autocmd = false },
    highlight = { enable = true, additional_vim_regex_highlighting = true },
})
