vim.cmd("let g:tex_flavor='latex'")
vim.cmd("let g:vimtex_quickfix_mode=0")
vim.cmd("let g:vimtex_compiler_method='tectonic'")
vim.cmd("autocmd BufWritePost *.tex :VimtexCompile")
vim.cmd("let g:vimtex_view_general_viewer = 'okular'")
vim.cmd([[let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex']])
vim.cmd("let g:vimtex_compiler_tectonic={'options': ['-X', 'compile', '-Z', 'shell-escape']}")
