require("plugins.core")

require("plugins.lsp")

require("plugins.alpha")
require("plugins.barbar")
require("plugins.vimtex")
require("plugins.wilder")
require("plugins.trouble")
require("plugins.lualine")
require("plugins.project")
require("plugins.whichkey")
require("plugins.gitsigns")
require("plugins.neoformat")
require("plugins.impatient")
require("plugins.colorizer")
require("plugins.ultisnips")
require("plugins.scrollbar")
require("plugins.telescope")
require("plugins.texconceal")
require("plugins.indentline")
require("plugins.treesitter")
require("plugins.toggleterm")
