vim.cmd("let g:tex_flavor='latex'")
vim.cmd("let g:vimtex_quickfix_mode=0")
vim.cmd("let g:vimtex_view_method = 'zathura'")
vim.cmd("let g:vimtex_compiler_method='tectonic'")
vim.cmd("autocmd BufWritePost *.tex :VimtexCompile")
vim.cmd("let g:vimtex_compiler_tectonic={'options': ['-X', 'compile', '-Z', 'shell-escape']}")
